// @ts-ignore
import pdfParse from "pdf-parse/lib/pdf-parse.js";


export interface ParsedArticle {
  title: string;
  category: string;
  meta_description: string;
  author: string;
  body: string;
}

const VALID_CATEGORIES = [
  "Brand",
  "Card",
  "Community",
  "Editorial",
  "Market-Intel",
];

function extractField(header: string, label: string, nextLabel: string | null): string | null {
  const pattern = nextLabel
    ? new RegExp(`${label}:\\s*([\\s\\S]*?)\\s*${nextLabel}:`, "i")
    : new RegExp(`${label}:\\s*([\\s\\S]*?)$`, "i");

  const match = header.match(pattern);
  if (!match) return null;

  return match[1].replace(/\s+/g, " ").trim();
}

export async function parsePdfArticle(
  buffer: Buffer,
): Promise<{ ok: true; article: ParsedArticle } | { ok: false; error: string }> {
  let text: string;

  try {
    const result = await pdfParse(buffer);
    text = result.text;
  } catch (err) {
    console.error("[parsePdfArticle] pdfParse threw:", err);
    return { ok: false, error: "Could not read this PDF file." };
  }

  const delimiterIndex = text.indexOf("---");
  if (delimiterIndex === -1) {
    return {
      ok: false,
      error:
        "This PDF doesn't have the expected header format. Make sure it was generated by the KLLCTRS content skill.",
    };
  }

  const header = text.slice(0, delimiterIndex);

  // If this PDF has other sections after the article (carousel, LinkedIn, etc),
  // stop the body at the article's own end marker instead of grabbing everything.
  const afterHeader = text.slice(delimiterIndex + 3);
  const endArticleIndex = afterHeader.search(/===\s*END ARTICLE\s*===/i);
  const body = (endArticleIndex === -1 ? afterHeader : afterHeader.slice(0, endArticleIndex)).trim();

  const title = extractField(header, "TITLE", "CATEGORY");
  const rawCategory = extractField(header, "CATEGORY", "META");
  const meta_description = extractField(header, "META", "AUTHOR");
  const author = extractField(header, "AUTHOR", null) || "KLLCTRS Editorial";

  if (!title || !rawCategory || !meta_description) {
    return {
      ok: false,
      error:
        "Missing TITLE, CATEGORY, or META in the PDF header. Check the file was exported correctly.",
    };
  }

  const category = VALID_CATEGORIES.find(
    (c) => c.toLowerCase() === rawCategory.toLowerCase(),
  );

  if (!category) {
    return {
      ok: false,
      error: `"${rawCategory}" isn't a recognized category. Expected one of: ${VALID_CATEGORIES.join(", ")}.`,
    };
  }

  if (!body) {
    return { ok: false, error: "No article body found after the header." };
  }

  return {
    ok: true,
    article: { title, category, meta_description, author, body },
  };
}