"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { UploadCloud, Loader2, FileText } from "lucide-react";

export default function ArticleUploadCard() {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);
  const [fileName, setFileName] = useState<string | null>(null);

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setUploading(true);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await fetch("/api/admin/content/upload", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();

      if (!res.ok) {
        toast.error(data.error ?? "Upload failed");
        return;
      }

      toast.success("Article imported as a draft", {
        description: data.draft?.title,
      });
      router.refresh();
    } catch {
      toast.error("Something went wrong uploading this file");
    } finally {
      setUploading(false);
      setFileName(null);
      if (inputRef.current) inputRef.current.value = "";
    }
  }

  return (
    <div className="rounded-2xl border border-violet-100 bg-white/80 backdrop-blur-sm shadow-lg shadow-violet-200/20 p-5">
      <h2 className="text-[10px] font-black tracking-[0.25em] text-[#5f2eea] uppercase mb-4">
        Upload Article PDF
      </h2>

      <input
        ref={inputRef}
        type="file"
        accept="application/pdf"
        onChange={handleFileChange}
        disabled={uploading}
        className="hidden"
        id="article-pdf-upload"
      />

      <label
        htmlFor="article-pdf-upload"
        className={`flex h-32 cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed transition-colors ${
          uploading
            ? "border-violet-200 bg-violet-50/50 cursor-wait"
            : "border-violet-200 hover:border-[#5f2eea] hover:bg-violet-50"
        }`}
      >
        {uploading ? (
          <>
            <Loader2 className="w-6 h-6 text-[#5f2eea] animate-spin" />
            <p className="text-sm text-[#4a3f6b]/60">Reading {fileName}...</p>
          </>
        ) : (
          <>
            <UploadCloud className="w-6 h-6 text-[#5f2eea]/50" />
            <p className="text-sm font-medium text-[#1a0a3d]">
              Click to upload a PDF
            </p>
            <p className="text-xs text-[#4a3f6b]/40 flex items-center gap-1">
              <FileText className="w-3 h-3" />
              Generated by the KLLCTRS article skill
            </p>
          </>
        )}
      </label>
    </div>
  );
}
