export const selectTriggerClass = `
h-11
w-full
rounded-xl
border
border-white/10
bg-[#FEF9FF]/[0.06]
text-left
text-sm
font-normal
text-white
transition
hover:border-[#9C7CF7]/40
focus:ring-2
focus:ring-[#9C7CF7]/20
focus:ring-offset-0
disabled:cursor-not-allowed
disabled:opacity-60
data-[placeholder]:text-white/40
`;
